### ISSUE TITLE
self-reference-survey: affect associations?

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#1172]
In the various tickets involving apt and pps, [like this](https://www.ess.stsci.edu/prsystem/servlet/prbrowse/pr.85698), there is reference to a flag called `self_reference_survey`. What is this? Does it affect associations? Is this something that is of import to the pipeline?

**Comment by hbushouse** [comment]
self_reference_survey can apply to NIRCam and MIRI coronagraphic observations, as well as NIRISS AMI observations. If the user doesn't select dedicated PSF observations, the science observations are declared to be "self referencing."

**Comment by hbushouse** [comment]
To follow up a bit more, in the case of NIRISS AMI observations, which go through the calwebb_ami3 pipeline, a self-referencing observation will result in an ASN that only contains science target exposures (no PSF target exposures). The calwebb_ami3 pipeline is already setup to handle this possibility, in which case the ami_analyze and ami_average steps will only be executed for the science target exposures and the ami_normalize step will be skipped. For self-referencing coronagraphic observations, the calwebb_coron3 pipeline will currently abort processing when it finds that no PSF exposures are present in the ASN. Eventually we will need to upgrade the calwebb_coron3 pipeline to allow the stack of science target data to be used as its own reference data (in keeping with the "self referencing" designation). This is possible with the use of the KLIP step to do PSF subtraction, because it is capable of examining the stack of science target data and finding those that are most suitable for use as references.

**Comment by stscieisenhamer** [comment]
Thanks. So, the current state of the associations which:

1. Allow AMI without PSF's
2 Do not allow CORON without PSF's

is acceptable, and no other associations are affected.
