### ISSUE TITLE
NRS_LAMP associations

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#1411]
Prompted by [DR#004441](https://www.ess.stsci.edu/prsystem/servlet/prbrowse/dr.4441), request clarification on what to do with `EXP_TYPE == NRS_LAMP`.

Currently, as listed in #1188, no level2b processing is done.  Similarly for level3, no rules explicitly include this.

However, the DR implies calibration similar to `NRS_FIXEDSLIT`. Right now that includes only `calwebb_detector1`.

**Comment by hbushouse** [comment]
For now it's fine to leave NRS_LAMP on the "no level-2b" list, because these exposures can be taken using the IFU, MSA, or fixed-slits, all of which require different forms of level-2b processing, hence it could be dangerous to even attempt to apply fixed-slit level-2b processing to them (dangerous in the sense that if it's IFU mode, for example, the calwebb_spec2 pipeline would probably crash with either reference file or processing problems).
