### ISSUE TITLE
Formalizing definition of member input path in associations

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#1544]
# Issue
Associations are constructed such that the exposure file names are just that, the file names. No presumption is made about the directory path to the exposure files.

Currently, `ModelContainer`, presumes that the association is co-resident with the exposures, prepending the directory path of the association to each of the exposure names.  

Question for the pipeline: Should there be a new option, `--input_dir`, that, when specified, would be prepended to all exposure names instead of the default above.

**Comment by philhodge** [comment]
If the option is `--input_dir`, I would expect the association file to be in that directory as well.

Why would we need to process files that are not in the default directory?  That is, can't the user just `cd` to the directory containing the files?  One reason why cd'ing to the directory might not work is if the files and directory are write protected, and the step or pipeline needs to write intermediate and output files.  An output directory can be specified, but what about intermediate files?  Since they may be the input to further processing, are they in the input directory or the output directory?  We run into that same problem if we specify an input directory and write to (a different) default directory.  I ran into this problem when I was wondering how to implement an input directory for STIS, and I didn't find a good solution.

**Comment by stscieisenhamer** [comment]
With respect to `Step`/`Pipeline` code, this issue is resolved in that files referenced by an association are co-resident with the association file.

Otherwise, from a user standpoint, it may be best to leave the handling up to the use-case and not try to specify a convention.

Will re-open/open new issue if this this needs to be re-addressed.
