### ISSUE TITLE
Naming of level3 versions of PSF inputs

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#1598]
# Issue
For `calwebb_ami3`, the PSF inputs get processing and are saved out as both Level2c and Level3 products. Level2c get the standard exposure-name-modified naming convention.

However, the Level3 naming is undetermined.

# Resources
- General notes about the calwebb_ami3 pipeline are now at https://confluence.stsci.edu/display/SCSB/CALAMI3+Development+Notes

# Implementation
Handle as one product, containing all science and PSF target exposures
- [x] bump versions
- [x] tests
- [x] Rule updates
    - [x] Find all Target and PSF exposures (from potentially multiple PSF targets)
- [x] `calwebb_ami3`
    - [x] update top level `process` to identify the science and psf members, and process accordingly.
    - [x] In the event that a user runs the calwebb_ami3 pipeline off-line and sets `save_averages=true`, the outputs from the ami_average step will be saved to files composed of the ASN product name, with an index number (for uniqueness) and suffix of _amiavg attached.
    - [x] The output of each call to the ami_analyze step will continue to be saved in a file that uses the input level-2b exposure-based name, with the <ac_id> and _ami suffix attached.
    - [x] The output of the ami_normalize step will also continue to be saved in a file that uses the ASN product name, with the _aminorm suffix attached.
    - [x] #1595 
- [x] tests
- [x] bump versions

**Comment by hbushouse** [comment]
Now that the APT implementation has put Science target and PSF target exposures into separate observations, we should update the asn_generator rules to create an ASN table that defines 2 products: 1 for the Science target and 1 for the PSF target. They'd each contain their respective level-2b exposures as members, and we can then use the unique product name for each one for their level-3 outputs. The PSF observation will generate only 1 level-3 output, which is the result of the ami_average step. The Science observation will generate 2 level-3 outputs: 1 from the output of the ami_average step (product type "amiavg") and 1 from the output of the ami_normalize step (product type "aminorm"). The latter is the final ("main") output of the calwebb_ami3 pipeline.

**Comment by hbushouse** [comment]
So the example ami3 ASN table previously constructed as an example for DMS (/grp/jwst/ssb/test_build7.1/examples_for_dms/level3/calwebb_ami3/jw87600-a3001_20170327t343434_ami3_001_asn.json) is no longer valid, because it defines a single product containing both science and psf exposures as members, and also uses a "psf_name" attribute to define the output product name for psf exposures.

In the new scheme we would have an ami3 ASN file that would be structured like this:
```
    "target": "1",
    "products": [
        {
            "name": "jw87600-a3002_t1_niriss_f480m-nrm",
            "members": [
                {"exptype": "SCIENCE",
                  "expname": "jw87600027001_02101_00001_nis_cal.fits"},
                {"exptype": "SCIENCE",
                  "expname": "jw87600027001_02101_00003_nis_cal.fits"},
                {"exptype": "SCIENCE",
                  "expname": "jw87600027001_02101_00002_nis_cal.fits"},
            ],
        },
        {
            "name": "jw87600-a3002_t2_niriss_f480m-nrm",
            "members": [
                {"exptype": "PSF",
                  "expname": "jw87600027001_02101_00004_nis_cal.fits"},
                {"exptype": "PSF",
                  "expname": "jw87600027001_02101_00006_nis_cal.fits"},
                {"exptype": "PSF",
                  "expname": "jw87600027001_02101_00005_nis_cal.fits"}
            ],
        }
    ]
```
The only slight oddity with this is that there's a single `target` attribute for the whole table and by default (I guess) it's set to the target id of the science product. Meanwhile the names of the defined products in the table body use two different target id's (1 and 2 in this example).

So now the ami_analyze step uses all of the exposure-based _cal members as input and produces a new exposure-based _ami product for each. The ami_average step then produces a source-based _amiavg product for targets 1 and 2, using the source-based product root names given in the ASN table. Finally, the ami_normalize step produces a source-based _aminorm product for only the science target, again using the source-based product root name given in the table (in this case for target 1).

@stscieisenhamer do you concur?

**Comment by stscieisenhamer** [comment]
The pipeline would need to identify which product was which by examining the `exp_type` fields, but I think that is fair.

**Comment by hbushouse** [comment]
The latest version of APT now allows for the user to select more than 1 PSF reference target (just like for coronagraphy). So the above scheme could be modified in one of several ways:

1. Define a level-3 product in the ASN table for each PSF target, in addition to the science target. This has the advantage of specifying a unique level-3 source-based product name for each of the PSF targets, which would be used for naming the `amiavg` product for each PSF target. This has the _disadvantage_, however, of creating separate `amiavg` products for each PSF target, when we really need to have only one created that is the average over all exposures from all PSF targets. That's what's needed as input to the final `ami_normalize` step of the ami3 pipeline.

1. Define a single level-3 product for all of the PSF targets, which would contain all PSF exposures as members. This has the advantage of giving us a single `amiavg` product for all PSF exposures, which is what we need, but has the problem of what source-based name to use for the product. It contains data from multiple targets, so what target id gets used in the product name? Concatenating all the target id's together into the name is not a nice solution (IMHO).

  I see two possible ways of getting around the product name problem:
   - Use the target id of only the first PSF target and the regular `amiavg` product type
   - Use the target id of the science target, which means the root name will be identical to the science product, and hence a different product type suffix could be used in order to maintain a unique file name. A product type of something like `psfamiavg` or `psf-amiavg` could be used.

A final possible approach is to not bother to define or save the PSF `amiavg` product at all (just pass it along in memory in the calami3 pipeline), in which case the product name goes away and all PSF exposures could be lumped in as members of the science target product, as is done with coronagraphy.

**Comment by hbushouse** [comment]
General notes about the calwebb_ami3 pipeline are now at https://confluence.stsci.edu/display/SCSB/CALAMI3+Development+Notes

**Comment by hbushouse** [comment]
New approach for the whole ami3 ASN scheme:

There's no need to define separate products in the ASN file for each PSF target, because the pipeline never needs to produce anything that is target-specific. All PSF exposures, from all PSF targets, are processed together in the ami_average step, resulting in a single PSF average product.

Furthermore, at the request of the AMI WG, there's no desire to save the averaged products (for either the science target or PSF targets) in regular operations, which is why the calwebb_ami3 parameter 'save_averages' has a default value of False. Because the averaged PSF product is not being saved, there's no need to worry about how to name the output file, hence we don't need a separate PSF product defined in the ASN file.

So, we will go back to the scheme of having a single product defined in the ASN file, which will have a product name corresponding to the science target, and all science target and PSF target exposures will be members of that one product.

The output of each call to the ami_analyze step will continue to be saved in a file that uses the input level-2b exposure-based name, with the <ac_id> and _ami suffix attached.

The output of the ami_normalize step will also continue to be saved in a file that uses the ASN product name, with the _aminorm suffix attached.

In the event that a user runs the calwebb_ami3 pipeline off-line and sets `save_averages=true`, the outputs from the ami_average step will be saved to files composed of the ASN product name, with an index number (for uniqueness) and suffix of _amiavg attached.

**Comment by stscieisenhamer** [comment]
# Question
Back to the `save_averages` option. As best as I can tell, there will only ever be two averages, the psf average and the science average. Would this be OK then to name the science average with a suffix of just '_amiavg', and for the PSF average, use '_psf_amiavg' or '_psf-amiavg'?  Then there would be no need for indexing, or anything other fancy. Since this is not an SDP archive product, it really doesn't matter what the suffix is, as long as it is explained to the user in the docs.  Note: I go for the '_psf-amiavg', with the hyphen.

**Comment by hbushouse** [comment]
Using a unique product suffix for ami_average results of PSF targets is certainly a reasonable approach. My only reservation is that it really isn't a different type of product than the "amiavg" product for science targets; it's simply a different target. So what we really should be doing is making the target_id field unique in some way, rather than the product type field. For example, append "-psf" to the end of the target_id ("t1-psf"), signifying that this file contains the amiavg data that gets used with the target t1 amiavg data during processing. But that's probably a lot harder to do and may break other parts of the file naming infrastructure.

**Comment by stscieisenhamer** [comment]
the other issue with inclusion of target id is that there can be many of those. at least with the generic psf extension, it is clear that this is the result of just the psf data.

with respect to the "breaking naming convention stuff", since this is not a DMS-sanctioned data output, we can do whatever we want, within reason.

however, it seems that keeping the same root as the rest of the output helps indicate that this data was produced and used to produce the rest of the results.  also, users should know enough to realize that the psf data are based on other targets anyways.

another option is to completely leave it up to the user. Instead of the `--save_averages` being a boolean, it is the root name to use to save the files with. The outputs would then be `root_psf_amiavg` and `root_sci_amiavg`. Then it is not our problem at all.
