### ISSUE TITLE
failing stpipe test

### ISSUE THREAD

**Issue by nden** [STScI-JWST/jwst#1640]
Currently master is broken because of a failing test in stpipe (starting with the merge of the unrelated #1639 ). The test is `stpipe/tests/test_crds.test_crds_step`. What is being tested by this? Is the test still relevant or should it be removed?

@stscieisenhamer @hbushouse

**Comment by hbushouse** [comment]
Need to ask @jaytmiller about this. The test is coming back with a newer version of a NIRSpec flat reference file than before. Not sure why (updated CRDS context with new NIRSpec flats?)

**Comment by jaytmiller** [comment]
It turns out this test is for NIRCAM and the context is not fixed to 
force the same regression result.

jwst_0425.pmap included massive numbers of  NIRCAM FLAT files and 296 
replaced 105 as seen here:

https://jwst-crds.stsci.edu/difference/?file1=jwst_0424.pmap&file2=jwst_0425.pmap

Not forcing the context is appropriate from one perspective and it's 
relatively stable,  so off the cuff I think we should just update the 
test to expect 296 instead.   These are Mike's tests so I'm not deeply 
attached to them,  but they do reflect what Mike wanted to know.  Verdict?

Todd

**Comment by nden** [comment]
Thanks Todd! I don't mind keeping the test, it's not a huge burden. The last time it was updated was a year ago. I'll update it as part of another PR I'm working on.

**Comment by jaytmiller** [comment]
Awesome Nadia,  thanks!

**Comment by nden** [comment]
fixed in #1642
