### ISSUE TITLE
Level2b calibration exposures should not be included in Level3 associations

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#1716]
# Requirement
Exposures that are used as calibration for Level2b processing should not be included in Level3 associations as `science` exposures.  Such exposures include:

- off-target background
- imprint

# Resources
- #766 

# Implementation
- [x] bump version
- [x] tests
    - `pool_017` is the main example. test already marked `xfail`.
- [x] code
    - Filter out "non-science" exposures
- [x] tests
- [x] bump version

**Comment by stscieisenhamer** [comment]
# Question
Should such exposure still be included in level3 associations? Options are

1. Ignore them completely
2. Include them but set their `exptype` to what their intended use was, such as `background` or `imprint`.

Including them would be consistent with the existing requirement that target acquisitions and on-board calibration exposures, though not used by Level3 processing, still be in the association.

**Comment by hbushouse** [comment]
We could theoretically produce level-3 products for exposures that are confined to an individual background target. Who knows what serendipitous science might result? How hard would it be to have them create there own unique level-3 ASN, separate from the science target ASN? In other words, let's say someone linked 2 background targets to 1 science target. We would produce a single level-2b ASN that contains exposures from all 3 targets, because we need the background exposures to do level-2b calibration of the science target. But then we generate 3 separate level-3 ASN's, each of which contains only the exposures for their target (2 background and 1 science).

Alternatively we could define 3 products within a single level-3 ASN and they would each be processed independently of one another.

One potential problem we might run into with either of these scenarios is file name collision, in situations where a given background target was linked to more than one science target. We could end up creating multiple versions of the level-3 products for a given background and hence we'd need to ensure unique file naming.

**Comment by stscieisenhamer** [comment]
With respect to level2, there would be no issue.  Ignoring what K.Gordon just said, the backgrounds can go through 2b as would any other exposure.

With respect to Level3, the backgrounds' have their own targets. Hence they would get their own sets of associations and there should not be any name collisions.  There would not be any duplication, because the BACKGROUND association candidate will not make any Level3 associations, since that candidate is only for Level2b processing. The Level3 candidates would be based solely on the OBSERVATION candidates.

So, we can do this (again ignoring what K.Gordon says).

However, this does not answer the original question: Should these exposures be included in the related sciences' Level3 associations in a "book-keeping" way the target acqs/calibrations are now?

**Comment by hbushouse** [comment]
Regarding
```
Should these exposures be included in the related sciences' Level3 associations in a "book-keeping" way the target acqs/calibrations are now?
```
I would say no, it's not worth the effort. That information is available in the level-2b ASN.
