### ISSUE TITLE
Data models support for GAINFACT / meta.exposure.gain_factor

### ISSUE THREAD

**Issue by jaytmiller** [STScI-JWST/jwst#1810]
There have been requests on Jira CRDS-120 and CRDS-175 for additional checking of the gain factor used in the gain_scale step.   There's a desire to document it in general for:

    Dark???           W
    Bias???            W
    Saturation         W
    linearity             W
    Gain                  R
    Readnoise        W

where it is really only functionally required for the gain_scale step.  

It is currently a scalar value in the continuous range between 1.0 and 10.0 which is checked independently in CRDS.  W corresponds to a CRDS warning when absent.  R (required) corresponds to a CRDS error when absent.

To properly support the creation of reference files,  three things need to happen:

1.  GAINFACT needs to be added to additional reference file schema.
2.  The reference file DM structure needs to change from meta.gain_factor to meta.exposure.gain_factor to mirror the core schema used for datasets.
3.  The gain_scale step needs to be tweaked to the new DM structure.

This primarily makes the CAL code data models responsible for *naming* the parameter and mapping it onto FITS.  It remains optional in CAL and unconstrained.

**Comment by hbushouse** [comment]
Just to be explicit, the reason for adding the GAINFACT keyword definition to reference file data models that don't actually require it (dark, superbias, linearity, ...) is because ref files creators are being encouraged to include that keyword in those ref files as information/documentation and if they use our datamodels to create the ref files (which we're also trying to encourage) they need to have the keyword defined in the datamodel in order to get it to appear in the FITS file.

**Comment by hbushouse** [comment]
Fixed by #1811.
