### ISSUE TITLE
crds_client fetching incorrect dark reference file for MIRI IFU SLOW readout

### ISSUE THREAD

**Issue by PaddyKavanagh** [STScI-JWST/jwst#1823]
There appears to be an issue in fetching the correct dark reference file for MIRI IFU data with the SLOW readout mode. If I have two input datamodels where dm.meta.exposure.readpatt is FAST for one and SLOW for the other, crds_client fetches the same dark file, e.g.,

dark_name = crds_client.get_reference_file(dm, 'dark')
print(dark_name)

will return

<path-to-crds>/references/jwst/miri/jwst_miri_dark_0056.fits

in both cases. I've check the darks in crds and there are FAST and SLOW mode darks for the MIRIFUSHORT and MIRIFULONG detectors from CDP6 so they are there:

File                                     DETECTOR       READPATT    VERSION
jwst_miri_dark_0044.fits    MIRIFUSHORT SLOW            06.01.00
jwst_miri_dark_0056.fits    MIRIFUSHORT FAST              06.01.00
jwst_miri_dark_0057.fits     MIRIFULONG   SLOW            06.01.00
jwst_miri_dark_0050.fits    MIRIFULONG   FAST              06.01.00

**Comment by hbushouse** [comment]
It could be related to #1560, but after looking at the selection values for the MIRIFU* darks in CRDS I think it might also be due to those settings. I notice that for the 2 latest MIRIFUSHORT and MIRIFULONG darks, one of them has READPATT='SLOW', while the other has READPATT='N/A'. I believe the precedence rules in CRDS bestref will always give higher priority to the one with N/A, which is why it's always coming back with jwst_miri_dark_0056.fits for the result, rather than returning jwst_miri_dark_0044.fits (the one with READPATT='SLOW').

Need input from @jaytmiller to confirm.

**Comment by jaytmiller** [comment]
Is there some test data to evaluate this against?

To be crystal clear:  N/A is a wild card that will always give precedence to any exact match.   N/A is a kind of fallback used when nothing better can be found,  a catch all which really just discounts that parameter for the sake of weighted matching where each exact match counts as 1,  N/A counts as 0,  and the highest sum of all parameter matches wins.  (roughly).

**Comment by hbushouse** [comment]
I'm wondering why those ref files were assign READPATT='N/A'. I'm guessing the data actually come from FAST mode, they probably should've been installed with READPATT='FAST', instead of 'N/A'. But that's a question for someone like Misty (or whoever delivered them to CRDS) to confirm. That way they wouldn't override the SLOW ref file when trying to match a SLOW science exposure.

**Comment by jaytmiller** [comment]
Fishing around in the website Recent Activity (a general purpose audit log) I found 

https://jwst-crds.stsci.edu/browse/jwst_miri_dark_0014.rmap

where Rossy re-categorized FAST as N/A so that it could also match FASTGRPAVG.

To achieve that end the correct possible rmap update approaches are to set:  

1. READPATT=ANY  (a full weighted match of 1) 
2. READPATT=FAST|FASTGRPAVG

The Past Actions panel on any file details page shows things happening to the file,  including adding it to CRDS.

One thing to remember about CRDS is that files are *routinely* re-categorized in the rmaps so they don't have to be redelivered.

Without actual data,  I'm having a hard time following this.

**Comment by PaddyKavanagh** [comment]
Howard, I should have elaborated a bit more on my reference to #1560. I was running tests on simulator output with different settings. The output always has the same naming structure so the two files I was comparing had the same filename, resulting in crds using the same dark for both files as described in #1560 . If run the SLOW mode file only in the python session, crds has no problem finding the correct dark jwst_miri_dark_0044.fits.

**Comment by hbushouse** [comment]
Ah, OK, so that would suggest that the existing rmap entries are OK. It was the problem referred to in #1560 that was the real problem? The different data models had the same filename meta attribute, so the CRDS bestref was getting the same result even when you changed the readpatt value in the data model?

**Comment by PaddyKavanagh** [comment]
Here is some code to show what is happening:

>>>slow_file = 'SLOW/dark/det_images/det_image_seq1_MIRIFUSHORT_12SHORTexp1.fits'
>>>slow_dm = datamodels.MIRIRampModel(slow_file)
>>>print(slow_dm.meta.exposure.readpatt)
SLOW
>>>print(crds_client.get_reference_file(slow_dm, 'dark'))
/Users/patrickkavanagh/crds_mirror/references/jwst/miri/jwst_miri_dark_0044.fits


>>>fast_file = 'FAST/dark/det_images/det_image_seq1_MIRIFUSHORT_12SHORTexp1.fits'
>>>fast_dm = datamodels.MIRIRampModel(fast_file)
>>>print(fast_dm.meta.exposure.readpatt)
FAST
>>>print(crds_client.get_reference_file(fast_dm, 'dark'))
/Users/patrickkavanagh/crds_mirror/references/jwst/miri/jwst_miri_dark_0044.fits

It seems the bestref for a given reference type in the first instance of a particular filename is the one used for all subsequent instances. Running these commands loading the FAST file first results in both calls to crds_client returning jwst_miri_dark_0056.fits

**Comment by jaytmiller** [comment]
When was the last time you updated CRDS?   (Have you tried removing all possible instances of CRDS in your conda environment?  What does "conda list crds" say? )

**Comment by jaytmiller** [comment]
If you do:

% export CRDS_VERBOSITY=50

what kind of output do you get from CRDS?

**Comment by jaytmiller** [comment]
OK.  my apologies,  I asked the wrong question.   The real determining factor is the version of JWST cal code you're running,  and 0.9.0 is old enough that some revisions definitely had the CRDS data models caching that causes this sort of problem.

A CAL code update should address this if our guess is correct. 

What does "conda list jwst" say?  If that identifies the git hash,  we can tell for certain.

**Comment by PaddyKavanagh** [comment]
'conda list jwst' doesn't give the git hash:

jwst                      0.9.0.dev0               py35_0    http://ssb.stsci.edu/astroconda-dev

I will update to the latest build and see if that fixes the problem.

**Comment by PaddyKavanagh** [comment]
Can confirm that this is not an issue in the latest code so problem solved!

Howard, what is the policy on closing issues? Can I close this or do you or someone else at STScI have to do it? I will leave it open for now...

**Comment by hbushouse** [comment]
Your confirmation that it's no longer an issue is enough for us to close the issue. So I'm closing it now. Can always reopen later if something else is discovered.
