### ISSUE TITLE
TST: Use pytest xdist for parallel testing in pandokia

### ISSUE THREAD

**Issue by pllim** [STScI-JWST/jwst#1835]
According to @jhunkeler , currently on pandokia, "every test is executed serially, leaving 31 cores doing nothing." This is undesirable. Please consider using https://docs.pytest.org/en/3.0.0/xdist.html plugin to enable parallel testing of this package.

Disclaimer: `xdist` is not very useful when we switch to Jenkins due to limited resources.

**Comment by hbushouse** [comment]
That's interesting to hear that the tests are supposedly running serially, because when I look at the time stamps on the output files created by tests in the 4 or 5 different test subdirectories, they all have overlapping times, which suggests to me that there are at least 4 or 5 parallel processes running.

**Comment by jdavies-st** [comment]
1. Currently our nightly regression tests that run on pandokia are not being tracked here on Github. They're tracked on SVN. We should change that.  Can we do that soon?
2. Our current unit tests in this repository run serially via `pytest` in Travis CI due to limited resources (as above in Jenkins).  Pandokia is not used for these tests.

I do use `xdist` locally when running the unit tests, and it cuts down the runtime by an order of magnitude.  So agree that it would be great to do this when and where we can in our CI environments.

**Comment by pllim** [comment]
> Can we do that soon?

Be my guest! :+1: (Unless you want to wait for HST to take the plunge first.)

**Comment by pllim** [comment]
@jdavies-st , please also see #1208

**Comment by stscicrawford** [comment]
@stsci-hack : Pandokia can not currently be updated to improve performance.   Solution is to move to Jenkins.

**Comment by pllim** [comment]
You gotta move it, move it! :+1:
