### ISSUE TITLE
make_header script keywords problems

### ISSUE THREAD

**Issue by cracraft** [STScI-JWST/jwst#1876]
Hi, I tested the make_header script and have a few issues that I found:
MIRI Level 1 files: FILTER and BAND are missing for both Imager and Spectrum (IFU data) headers. These keywords are required in the Level 1 DETECTOR1 portion of the pipeline because MIRI has filter and band dependencies for some steps like Linearity. 

There are also what appear to be NIRSpec specific keywords NRS_NORM and NRS_REF included in the MIRI headers.

MIRI Level 2 headers: for Imager, MODULE is listed, though it seems to be a NIRCam keyword. For the IFU data, the MODULE keyword is also listed, along with NIRSpec MSA specific keywords: MSAMETFL, MSAMETID. Also in the IFU level two files, the keywords that indicate which reference steps are used and which steps in the pipeline are applied are listed, though those keywords don't show up in any other file.

MIRI Level 3 headers also include the MSA specific keywords and the MODULE keyword.

**Comment by hbushouse** [comment]
Regarding the lack of FILTER and BAND, this is a limitation in the way the script works. It's only looking for keywords that are needed by the calibration algorithms themselves, and none of the calwebb_detector1 step algorithms use them. They are needed, however, as you point out, in order to do reference file selection, for reference files like linearity (and some others need READPATT). We'll need to think about how to overcome this.

**Comment by stscicrawford** [comment]
Updates to the `make_headers` script were just merged in #1889 .  These can be accessed by updating directly from the repository.
