### ISSUE TITLE
Rule: Self-referential PSF's

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#1912]
# Issue
For coronagraphy and ami, in APT, a proposer can create _self referential_ observations. This is where all the science observations can also be considered PSF's and no observation is identified as a PSF. Create associations to handle this situation.

# Implementation
## AMI
`calwebb_ami3` inherently can handle this situation. No change required to the `Asn_AMI` rule.

## Coronagraphy
Current calibration code,  at least through version 0.9, has no specific processing for this situation. The current algorithm would call for all the science observations to be considered a stack of PSF's. This stack would be processed then applied against all the science observations. This would be implemented in an association by duplicating the science member list and assigning the duplicates the `psf` role.

## Tasks
- [ ] document
- [ ] bump version
- [ ] tests
- [ ] create rule for self-referential coronagraphy, based on rule `Asn_Coron`
- [ ] tests
- [ ] bump version
- [ ] document

# References
- [APT PR #90412](https://www.ess.stsci.edu/prsystem/servlet/prbrowse/pr.90412): Tangentially related bugs in APT as of v26.0.

**Comment by hbushouse** [comment]
The AMI case of self-referencing science observations is already accounted for in the logic of the `calwebb_ami3` pipeline. It is already setup to handle the case of not having a PSF observation in the ASN, and in that case only applies the first of the three steps in the pipeline (`ami_analyze`). So there's no need to produce a "fake" ASN where the science member is also listed as a PSF member. Only the science member needs to be listed.

**Comment by stscieisenhamer** [comment]
# Question
Hmmm, methinks this is a `calwebb_coron3` issue actually. If the logic is:
```
if no_psfs_found then use_all_science_as_psf
continue_processing
```
this logic should simply be in `calwebb_coron3` instead of the association generator. If the logic is more complicated than that, then the solution is definitely in `calwebb_coron3`.

Thoughts?

**Comment by hbushouse** [comment]
I think that implementing this logic in `calwebb_coron3` is just as good a place as any (rather than in the `asn_generator` and resulting ASN file that's produced). Eventually the handling of all PSFs will need to change anyway, once a PSF library becomes available in CRDS. Once that happens, then a self-referencing coron observation would just use the PSF library and/or a combination of the PSF library and the self-referencing science observations all stacked together. I suspect that the place all of that logic will need to be implemented is also in `calwebb_coron3`. So we might as well start with this case implemented in `calwebb_coron3`.

**Comment by stscieisenhamer** [comment]
Closing this issue and moving the coding issue to #2111
