### ISSUE TITLE
make_header keyword issues

### ISSUE THREAD

**Issue by cracraft** [STScI-JWST/jwst#2048]
I have recently re-tested the script make_header and encountered a few keyword problems. The NIRSpec keywords NRS_NORM and NRS_REF are still appearing in the headers. These keywords are related to IRS2 modes that don't pertain to MIRI. FILTER is now listed, which is good, but keywords like BAND and CHANNEL for IFU are still missing, as well as READPATT. These keywords may not be used in the pipeline, but are needed for CRDS reference file matching, so that part still needs to be done.

I have also noticed that in the listing of the reference files used, all possible reference files are listed, including those that do not pertain to MIRI, like R_MSAOPE, R_BARSHA, etc. Are these keywords meant to be included, or is there a plan to sort those out specifically by instrument as well?

Also, I don't know if this is important, since the exercise is to list the needed keywords and not necessarily their values, but the only DETECTOR I see listed in the headers is MIRIFULONG, even when it's an IMAGER header. EXP_TYPE is correct, but DETECTOR is not.

**Comment by bernie-simon** [comment]
There were several problems in the code which prevented the full set of keywords used to select reference files from being added to the output image.  I've addressed them in the latest update. The pipelines copy the reference file keywords from the input to the output image and then update the steps that were completed. For that reason all the reference file keywords must be in the input file. The set of default values for the miri have been updated so that it now distinguishes between exposure types.
