### ISSUE TITLE
extract_2d must include source information in the slits

### ISSUE THREAD

**Issue by nden** [STScI-JWST/jwst#212]
As this [comment](https://github.com/STScI-JWST/jwst/pull/207#issuecomment-245620576) clarifies `extract_2d` should use the MSA configuration file to include some (all?) source information in the slits.

**Comment by hbushouse** [comment]
The NIRSpec MSA configuration file source table contains the following fields:

program (int)
source_id (int)
source_name (string)
alias (string)
catalog_id (string)
ra (float)
dec (float)
preimage_id (string)
stellarity (float)

For each slit object that exists in the incoming WCS object (created upstream by assign_wcs), extract_2d creates a MultiSlit slit instance and then needs to populate meta data for that slit instance from the appropriate row of information in the MSA config file source table. The mapping between a slit instance and the appropriate row of information in the source table is accomplished via the source_id value, which will exist in the WCS meta data for the slit. Once the appropriate row is found, the following entries from the source table need to be copied to their corresponding slit meta attributes:

source_id -> model.slits[n].source_id
source_name -> model.slits[n].source_name
alias -> model.slits[n].source_alias
catalog_id -> model.slits[n].catalog_id
stellarity -> model.slits[n].stellarity

**Comment by hbushouse** [comment]
In addition to reading source information from the Source table in the MSA config file, this task should also read the "estimated_source_in_shutter_x" and "estimated_source_in_shutter_y" values from the Shutter table in the MSA config file and store those values in the slit meta data. Because there can be multiple rows in the Shutter table for a given slitlet_id, you must find the row that has 'background=N' (shutter does not contain background, hence contains the source) for each slitlet_id and retrieve the estimated x/y source locations from that row. These values should then be stored in the slit meta data attributes:

model.slit[n].source_xpos
model.slit[n].source_ypos

(which still need to be defined in the multislit schema).

When extract_2d is processing a NIRSpec fixed-slit (NRS_FIXEDSLIT) exposure, these 2 values should be set to defaults of 0.0.

**Comment by hbushouse** [comment]
PR #350 added the new source_xpos and source_ypos slit meta entries, so you're good to go.
