### ISSUE TITLE
calspec2 bogus product when MSAMETFL is not available

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#2151]
DMS testing of 0.9.6 has revealed that when ``calspec2`` is run on a NIRSpec MSA exposure and the MSAMETFL isn't specified or can't be opened, the way in which ``calspec2`` aborts processing results in a product being saved that has a file name of the form "jwxxxxxxx_nrs1_spec2pipeline.fits". We should look for a way to not return anything to `stpipe` in this case, so that no output product gets created at all.

**Comment by nden** [comment]
A few follow up questions:

- Should assign_wcs return the input data model in this case or should it return None?
- There are other cases in assign_wcs where a WCS pipeline was not created for some reason and the input data model is returned unchanged. Should it return None in those cases or keep it as it is? If we are to return the input model as the current implementation, what should the name be?

**Comment by nden** [comment]
It has been decided that this condition should raise an error and abort the pipeline. It should be implemented for build 7.2.

**Comment by stscieisenhamer** [comment]
# Question
`assign_wcs` will raise errors when errors occur. Consequently, `calwebb_spec2` will error out, by default.

👍 

However, what should `calwebb_spec2` do if, for some reason, `assign_wcs` ends up being `SKIPPED`? There are, at least, two situations when this can occur:

1. When explicitly told to be skipped: `calwebb_spec2.steps.assign_wcs.skip == True`
2. Despite `assign_wcs.skip == False`, after returning, the step has indicated it was `SKIPPED`, for some reason.

For 1, since it was specifically requested, I presume this would be a graceful exit, with informational messages.

For 2 however, is this another exception? Or just have `calwebb_spec2` produce strong language, much as it does now.?

**Comment by hbushouse** [comment]
It's probably OK to leave ``assign_wcs`` setup the way it is currently, in that it always returns a data model, even when it skips processing (the returned model is a copy of the input). That way people who are calling ``assign_wcs`` by itself interactively will always get something back.

But when this occurs within the ``calwebb_spec2`` pipeline, I guess the pipeline is going to have to check the value of both ``step.assign_wcs.skip``, which is set by the user, and ``model.meta.cal_step.assign_wcs``, which is set by the step. I can envision at least 1 use case where it's OK for ``calwebb_spec2`` to proceed even though the user asked for ``assign_wcs`` to be skipped, and that would be if they had previously applied ``assign_wcs`` to a data file and are now rerunning it through ``calwebb_spec2`` for some reason. Because ``assign_wcs`` was run previously, the WCS info that other steps in ``calwebb_spec2`` should be there.

The question is how much do we want to trust that everything needed is actually there when the step was skipped by the user?

So for scenario 1 above, we don't necessarily need to do a graceful exit when ``steps.assign_wcs.skip == True``. If ``model.meta.cal_step.assign_wcs == COMPLETE``, we could potentially proceed.

Scenario 2 should definitely NOT proceed with the rest of ``calwebb_spec2`` and in order to satisfy exit status requirements needed in the Ops environment, we should issue the existing ERROR messages and then raise an Exception, as opposed to just returning control to ``stpipe``.

**Comment by stscieisenhamer** [comment]
WRT to trusting the situation when `skip == True`: At that point, all that can be done is take the "OK, but ..." attitude and continue on.

Will research, but question: What happens if the input has marked a step `COMPLETE`, but on subsequent runs, the user has requested `skip=True`. Does the model get updated to say the step is now `SKIPPED`? I would think it should remain `COMPLETE` because it was completed anyways, but not sure what the standards are on this.

Otherwise 👍

**Comment by philhodge** [comment]
If a file that's input to calwebb_spec2 has S_WCS = 'COMPLETE', I think the pipeline should accept that.  This won't happen in the DMS pipeline (will it?), so the only potential problem is when a user is running the pipeline off-line.  If `assign_wcs` needs to be run again due to some backward-incompatible updates, the user will get an exception in a later step, with hopefully enough information that the user will know what to do.
If `skip = True` was specified for `assign_wcs`, the pipeline has absolutely no right to change S_WCS to 'SKIPPED'.  If `assign_wcs` was run and was successful, it wasn't skipped, it was complete.

**Comment by stscieisenhamer** [comment]
# Implementation
- [ ] documentation
- [ ] tests
    - [ ] case for missing `msametfl` file
- [ ] code
    - [ ] check logic on step status
    - [ ] `calwebb_spec2` checks around `assign_wcs`
- [ ] tests
- [ ] documentation

**Comment by jdavies-st** [comment]
If downstream steps require there to be a GWCS object in the input file, what should be the best way to check this?  Check that `model.meta.cal_step.assign_wcs == 'COMPLETE'` or just see if there's a GWCS object in the correct location, ignoring the keyword?

Currently, only `flat_field_step` check ifs `cal_step.assign_wcs == 'COMPLETE'` in order to proceed.  No other steps have these checks for any `cal_step.xxxx` values.  Several pipelines do, but that's mostly for purposes of flow control within the pipeline.

**Comment by nden** [comment]
Here is the full list of cases where assign_wcs is skipped. In these cases the input model is returned and a description of the problem is printed. Please advise if any of these are not handled correctly:

- Nirspec IFU on NRS2 detector with a mid-resolution grating.
- Nirspec IFU on NRS2 when grating=G140H and filter=F070LP
- Nirspec FS or MSA observation where no open slits are detected or the open slits do not project on the detector.
- If no reference files were provided.
- For some EXP_TYPE values, there's currently no WCS implemented. These are:

FGS: "FGS_SKYFLAT", "FGS_INTFLAT", "FGS_DARK"
MIRI: "MIR_FLATMRS", "MIR_FLATIMAGE", "MIR_DARK"
NIRCAM: "NRC_LED", "NRC_DARK", "NRC_FLAT"
NIRISS: "NIS_DARK", "NIS_LAMP"
Nirspec: 'NRS_AUTOFLAT', "NRS_AUTOWAVE', 'NRS_DARK'

"NRS_AUTOFLAT" should be processed like a MOS observation [comment](https://github.com/STScI-JWST/jwst/issues/1188#issuecomment-386276107)
What about the rest of them? #1188 lists them all under no level2b processing. So I'd think it's safe to keep the code as it is, i.e. return the input model and skip the step, in case a user runs assign_wc son one of them.

**Comment by stscieisenhamer** [comment]
@nden @jdavies-st With respect to the latest comments considering how to check/handle possible "bad" situations, this seems to be a general architecture question. I don't believe there is a standard?  If agreed, please add the subject to #2159.

**Comment by jdavies-st** [comment]
Yeah, agree it is a general architecture question.  I'll add it to the other issue.
