### ISSUE TITLE
resample should use skymatch results

### ISSUE THREAD

**Issue by jdavies-st** [STScI-JWST/jwst#265]
Currently resample ignores the `model.meta.skybg` keyword when it does its final resampling.  This needs to be implemented for both the `calwebb_image3` and `calwebb_spec3` pipelines.

**Comment by hbushouse** [comment]
Definitely should be implemented for use in calwebb_image3, where the result of sky matching will be a simple scalar value for each image. In the case of spectroscopy the only mode that will make use of sky/background matching is the MIRI MRS, because the background emission at mid-IR wavelengths will be more variable and problematic than the near-IR spectroscopic modes. For the MIRI MRS the sky matching algorithm that Mihai is working on implementing will be able to compute polynomial solutions to the background in each exposure, because there could be gradients of unknown order. So the background in this spectroscopic mode will not be represented by a scalar. We will need a dedicated routine to evaluate the polynomial fits for each exposure and subtract them.

**Comment by stsci-hack** [comment]
Work done in #1761 should resolve this issue.
