### ISSUE TITLE
WCS domain used by extract_2d

### ISSUE THREAD

**Issue by philhodge** [STScI-JWST/jwst#281]
The domain information from the WCS is used for the lower and upper limits of a slice, in order to extract a 2-D cutout from the input image.  The lower limits in X and Y are later assigned to attributes that correspond to FITS keywords SLTSTRT1 and SLTSTRT2.  The domain limits are zero-based, while the FITS keywords are one-based.  Therefore, 1 should be added to `xlo` and `ylo` before they are assigned to attributes `xstart` and `ystart`.

The `extract_2d` step assumes that these limits are inclusive.  It would be preferable if the step checked the 'includes_lower' and 'includes_upper' key values to see whether to include the lower and/or upper limits.

Are the values of the domain limits required to be integers?  The values are used directly, without rounding or truncating to integer.  If the domain limits can be float, it would be safer and more explicit to convert to integer before being used as the limits of a slice.

The `extract_2d` step creates a domain for the WCS for the extracted slice ("slit"), and the step assigns fractional values for the limits.  Is it OK for the domain limits to be float?

**Comment by nden** [comment]
@philhodge Most of your concerns are addressed in #283.

`extract_2d` makes the general numpy slicing assumptions - "lower" is inclusive, "upper" is not.
`assign_wcs` writes the `domain` in that way. Do you think we should actually check again? Maybe a user can modify the domain?

Someone had requested before that the values of the domain are the actual boundaries in the detector, that's why floats appeared before. We have an agreement now that domain will reference the center of the pixels and applications will have to adjust if they need the actual boundary. So domain values will be integers.

Feel free to close this when you think appropriate.
