### ISSUE TITLE
Spec2Pipeline not honoring output_file parameter

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#282]
M.Wolfe [reports](https://footprints.stsci.edu/MRcgi/MRTicketPage.pl?MRP=0dc1c9801f4174c9b2e0a5c3068eef51b&USER=eisenham&PROJECTID=3&MAJOR_MODE=DETAILS&MR=9313&DOWHAT=JUMPTOTICKET&MR=9313&DIRECTLOGIN=1&), using the Build6 version, that Spec2Pipeline is not honoring the `output_file` parameter. Report is in next comment. Filing an issue because I cannot confirm whether this is currently the case or not.

**Comment by stscieisenhamer** [comment]
```
Hi,

Here is facsimile of a python module that I use to calibrate data up
through level 2B for spectroscopy:

import os
import glob
import time
import numpy as np
from astropy.io import fits
from jwst_pipeline.pipeline.calwebb_spec2 import Spec2Pipeline

def cal_2B_spec(sci_file1):
"""
Description
-----------
This script takes a raw dark file and treats it as a science image by
editing the FILTER and PUPIL header keywords.
The configuration (.cfg) has the calibration steps that are to be
completed. Steps to be skipped are marked with 'skip = True'.

1) Gather the science dark reference file and put into a list.
2) Run the JWST calibration pipeline 2B steps.
3) Output science file that has been put into level 2B.

Parameters
----------
sci_file1: list
input sci_file1
"""

start = time.time()

for i, filename in enumerate(sci_file1):
Spec2Pipeline.call(filename, config_file='cal_niriss_spec_2B.cfg',
output_file='soss_2B_corrected_results_%03d.fits' %(i+1))
print 'Done with one file ... moving on to the next one.'

rm_list = glob.glob('real*_nint_*.fits')
for filename in rm_list:
if os.path.exists(filename):
os.remove(filename)
else:
print 'Could not find file: ', filename

rm_list = glob.glob('soss*_refpixcor_*.fits')
for filename in rm_list:
if os.path.exists(filename):
os.remove(filename)
else:
print 'Could not find file: ', filename

end = time.time()
tot_time = end - start

print 'Done, Done, and Done. Git the bleep along little doggies!!! Total
run time in seconds: ', tot_time

if __name__ == '__main__':
sci_file1 = sorted(glob.glob('soss_2A_results_int_*_2B.fits'))
print sci_file1
cal_2B_test(sci_file1)


It seems that the pipeline ignores the output_file
='soss_2B_corrected_results_%03d.fits' %(i+1) and spits out the same data
product but with a different name: file:
soss_2A_results_int_00001_cal.fits
This is alright for now as I will just rename the file but I thought that
this should be reposted. Let me know if ther are any questions.

-Michael
```

**Comment by hbushouse** [comment]
The latest development version of the calspec2 pipeline does not solve this issue either. And there 2 reasons why it doesn't or can't be done, at least not easily.

1) The calspec2 pipeline is setup to run on either an association of multiple products or a single product. If an association is used, it makes no sense to specify a single output_file name, because multiple outputs are created (one for each input).

2) Even when a single exposure is processed, the calspec2 pipeline produces multiple types of output products: a calibrated, unrectified 2D image, a calibrated, rectified/resampled 2D image, and a 1D extracted spectrum. So again, it doesn't make any sense to specify a single output_file name, because which output product would it map to? You could use it for the final (1D extracted spectrum) product, but then the intermediate products would end up with completely different names that would be based on their input names.

**Comment by hbushouse** [comment]
That's certainly a possibility and is analogous to the way in which output product names are now specified in ASN tables. In many cases of ASN processing there will be multiple types of output products generated, so the output product name in the ASN table is only a root name and the pipeline module itself finishes the construction of the appropriate file names for each product by adding a suffix and extension. That would at least cover the case of multiple product **_types_**. But in calspec2 you're also producing outputs for each of the individual input members, in which case you can't use the same single root name for all of them, because as soon as you process the 2nd member you'd start clobbering the files already saved for the 1st member.

I suppose some additional logic could be added to the pipeline module that would allow for the use of a user-supplied output root name when you're only processing a single exposure, but would then issue a warning that it can't be used when processing multiple exposures from an ASN table and would ignore it and use the regular methods based on the root of each input file name.

**Comment by philhodge** [comment]
The user can't supply the complete output file name, no, but even for an 
output for an individual input member, you could start with a 
user-supplied prefix (e.g. a directory) and append the input file name 
as a suffix.  We should at least have the option to read files from one 
directory and write files to a different directory.

**Comment by hbushouse** [comment]
Yes, we do already have the --output_dir option available, and it works (I just tried it with calspec2), such that all output files can be put into a different directory than the input or working directory. The folks in SDP requested this a while back, so we implemented it in Build 6.

**Comment by stscieisenhamer** [comment]
As of pr #897 Spec2Pipeline should honor the `output_file` and `output_dir` directives correctly, as used above. With respect to associations, the user should modify the association to handle the naming, at the moment.
