### ISSUE TITLE
Task: Extract_1d updates for Build 7

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#324]
There are several updates we need to make to the extract_1d task in order to have it operate properly within the calspec2 and calspec3 pipelines for Build 7.
- [x] Update the types of columns stored in the output table
- [x] Apply flux calibration to the extracted 1D countrate spectrum
- [x] Updates to extract spectra from an input IFU cube
- [x] Updates to allow for resampled input models

**Comment by hbushouse** [comment]
**Table columns**

The spectroscopic working group has requested the following columns of output data:

> Required columns of the binary table:
WAVELENGTH, wavelength (μm)
FLUX, background-subtracted flux density (mJy)
ERROR, uncertainty in background-subtracted flux density (mJy)
DQ, the logical OR of the DQ values of all pixels contributing to this wavelength bin.

> For now, any additional columns are allowed.  Possibilities include
NET, background-subtracted counts (DN/s/pixel)
NERROR, uncertainty in background-subtracted counts (DN/s/pixel)
BACKGROUND, background model (DN/s/pixel)
BERROR, uncertainty in background model (DN/s/pixel)

So we need to remove the existing column called "column" (which just gave the pixel coords within the image), and add at least FLUX, ERROR, and DQ columns.

**Comment by hbushouse** [comment]
**Flux calibration**

Flux calibration conversion factors and sensitivity vectors will be available in the input product. The "relsens" attribute of the data model contains a table with wavelength and response arrays that can be applied to the countrate spectrum. Linear interpolation should be used to evaluate the flux cal response values on the wavelength grid of the extracted spectrum. The extracted countrate spectrum should be multiplied by these response values, with the results stored in the FLUX column of the output table.

**Comment by philhodge** [comment]
Should the column names be upper case?  The current names are lower 
case, and this is the time to change the case if we want to do so.

**Comment by philhodge** [comment]
Should the floating-point columns (i.e. everything except DQ) be double 
precision?  These are not large files, after all.  For TSO at least, I 
would think everything should be done in double precision.

**Comment by hbushouse** [comment]
For table column names: isn't this the issue that gave us lots of trouble recently with names being in lower case in the data model schema, but FITS stores them as upper case? What was the resolution of that? Do the data models now support table column names as being case-insensitive? According to astropy.io.fits docs, that library treats table column names in a case-insensitive way, even though the actual names as stored in the TTYPEn keyword values can have variable case. Perhaps we should just always use all upper-case to be safe? It can be annoying having to type them in upper-case when you want to access the attributes in a data model you've got loaded, but perhaps that's the safest and most robust approach?

**Comment by hbushouse** [comment]
Double precision: I think you're right that it can't hurt to use float64 for everything but DQ. Not sure how many significant digits are needed to see the relative variations as a function of time for TSO observations, but it would be a shame to inadvertently restrict it by the data type in the product.

**Comment by philhodge** [comment]
The problem (issue #179) had to do with a data model that had lower-case 
column names, and I tried to use the model to read an existing table 
that had upper-case column names.  This worked for most tables, but 
under some conditions (there was a column that contained arrays, maybe 
there also had to be a character-string column), the column values came 
back empty or zero.  Bernie has fixed this, but I haven't checked since 
then.

FITS doesn't change column names in tables; either case works fine.  
astropy.io.fits treats column names in a case-insensitive way, yes, but 
there had better not be a conflict (e.g. both "net" and "Net" in the 
same table).  I don't know what will happen with tables in asdf files.  
For HST we used upper-case names, and I don't think it would hurt to use 
upper-case names for JWST.

Phil

**Comment by hbushouse** [comment]
👍

**Comment by bernie-simon** [comment]
> On Oct 7, 2016, at 10:19 AM, Howard Bushouse <notifications@github.com> wrote:
> 
> For table column names: isn't this the issue that gave us lots of trouble recently with names being in lower case in the data model schema, but FITS stores them as upper case? What was the resolution of that? Do the data models now support table column names as being case-insensitive? According to astropy.io.fits docs, that library treats table column names in a case-insensitive way, even though the actual names as stored in the TTYPEn keyword values can have variable case. Perhaps we should just always use all upper-case to be safe? It can be annoying having to type them in upper-case when you want to access the attributes in a data model you've got loaded, but perhaps that's the safest and most robust approach?


There was a bug in the datamodels code that resulted from the case of the table column names in the numpy record not matching the case of the names in the fits table. It was fixed by setting the numpy record field names to the fits table names. Now you should also be able to retrieve table columns from a datamodel in a case insensitive way.

**Comment by hbushouse** [comment]
**Resampled input models**

The task currently works on ImageModels and MultiSlitModels as input. In addition to these types, it must also be able to work with inputs that have been resampled/rectified. For 2D (slit) spectra, these would most likely be DrizProductModels, while for 3D (IFU) spectra they would be IFUCubeModels. DrizProductModels contain arrays of SCI, CON, WHT, and RELSENS data, corresponding to attributes data, con, wht, and relsens. IFUCubeModels contain arrays of SCI, ERR, DQ, and WMAP (weight map) data, corresponding to attributes data, dq, err, and weightmap.

The ability to work with unresampled Image and MultiSlit models must be retained for those observing modes where the users do not want the 2D data resampled, which is mainly time-series modes like MIRI LRS slitless and NIRISS SOSS.

**Comment by philhodge** [comment]
When extracting from an IFU cube, the astropy photutils is currently used for a circular extraction region (i.e. a point source), but it should also be used for a rectangular extraction region (i.e. for an extended source).

Rather than trying to use some of the same keys (for a JSON reference file) for extracting from an IFU cube as for a 2-D input image, the keys should closely match those in photutils for a circular or rectangular aperture.  The rotation angle of a rectangular aperture should be specified in the JSON file in degrees rather than radians, however.  Most or all of the JSON keys should have default values.  In particular, for `x_center` and `y_center`, the default should be the center of the input IFU image (the sky image).  The default for `radius` should be one quarter the length of the smaller of the image axis lengths.  The default for `width` and `height` should be half the smaller image axis length (since `width` and `height` are the full width and height respectively).

**Comment by hbushouse** [comment]
All updates necessary for baseline operation in B7 have been completed.
