### ISSUE TITLE
write a simple WCS if only one slit is open

### ISSUE THREAD

**Issue by nden** [STScI-JWST/jwst#523]
Given a list of potentially open slits, the NIRSpec WCS pipeline checks if any of them fall outside the detector and removes them from further processing. In addition a subarray o fonly one slit is also a valid observation. In this cases assign_wcs should create a simple WCS. Currently it creates a complex WCS object with only one simple WCS in it.

**Comment by jdavies-st** [comment]
Will the slit subarray with the simple wcs need to then be run through extract_2d?

**Comment by nden** [comment]
No, not in this case. Is there a reason to do so?
However, the details of how steps after assign_wcs will know which subarray it is will need to be worked out.

**Comment by jdavies-st** [comment]
It was the metadata I was thinking about.  Perhaps extract_2d could treat these as a special case, and just populate the metadata so that this ImageModel looks the same as the ImageModels contained in the model.slits of the MultiSlit model.

**Comment by hbushouse** [comment]
Skipping extract_2d for NIRSpec exposures that contain only 1 slit to begin with should result in the same kind of datamodel and flow as a MIRI LRS fixed-slit exposure, which also contains only 1 slit and does not go through extract_2d. So in both cases you'd get an ImageModel (rather than a MultiSlitModel) as input to downstream steps like flat_field and resample_spec. If they can already handle the MIRI LRS fixed-slit case, I would think they could handle the NIRSpec single slit case too.

**Comment by nden** [comment]
Done in #1250 .

**Comment by hbushouse** [comment]
The consensus now is to always have extract_2d create a MultiSlitModel as output, even when only a single slit is being used in an exposure. Even when a subarray readout is used to isolate the data to the region of a single NIRSpec fixed slit, extract_2d is still executed, because the domain of the instrument model for the slit is somewhat smaller than the subarray, so an extraction is still done. In this case it makes sense, for consistency, to put the data into a MultiSlitModel containing 1 slit.

**Comment by hbushouse** [comment]
This does NOT apply in the case where EXP_TYPE='NRS_BRIGHTOBJ', for which extract_2 produces a CubeModel (the data are 3D).

@philhodge Can the flat_field step handle a CubeModel as input for a NIRSpec fixed-slit? This mode will always use the S1600A1 slit.

**Comment by philhodge** [comment]
No.  For NIRSpec, flat_field expects an ImageModel.  I'm not sure what would be involved in having it loop over the first axis, which I think is what is needed.

**Comment by hbushouse** [comment]
Fixed by #1250 (extract_2d), #1321 (extract_2d), and #1351 (flat_field).
