### ISSUE TITLE
Is this in Astroconda yet?

### ISSUE THREAD

**Issue by pllim** [STScI-JWST/jwst#59]
See FootPrints Issue 8921

**Comment by hbushouse** [comment]
I don't know if the new jwst package is in astroconda yet, but if it is, Michael is using incorrect imports. He's modified jwst_lib to jwst.lib, which is what we told everyone to do about a week ago before the decision was made to go with a flat package structure, as well as deciding to rename "models" to "datamodels", so he needs to use "jwst.datamodels" in place of "jwst_lib.models".

**Comment by pllim** [comment]
I don't know what is the right answer to tell him then... @jhunkeler ?

**Comment by jhunkeler** [comment]
We can't submit `jwst` to astroconda until astropy makes a release. I'll just get him setup with the dev stuff...

**Comment by nden** [comment]
Is the package going in `astroconda` or `condadev`? Is `astroconda` updated every night? I thought this was our release.

**Comment by hbushouse** [comment]
I think that at one of the discussions we had within the past week or so we had decided against putting this in astroconda for now, because we don't want this to be a public release, and so the only option left was to put it into conda-dev. We have to put it into one or the other in order to make new/latest versions available, because ssbdev is no longer being updated (it's essentially frozen to the Build 6 delivery).

**Comment by jhunkeler** [comment]
Resolved 8921 -- Mike's happy.

**Comment by pllim** [comment]
Thanks!
