### ISSUE TITLE
Task: Flat-fielding for NIRSpec imaging exposures

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#610]
The new NIRSpec flat-fielding scheme implemented in Build 7 did not include any methods (or reference files) for correcting imaging-mode exposures, like target-acqs. This capability needs to be implemented for Build 7.1.

**Comment by philhodge** [comment]
This can be done as follows:  In flat_field_step.py, add an ``IMAGING_MODES`` list to specify all known values of EXP_TYPE that indicate NIRSpec imaging data rather than spectrographic (see ``exp_type2transform`` in assign_wcs/nirspec.py).  Replace the ``is_NIRSpec`` flag with ``is_NRS_spectrographic``.  Set the latter to True for NIRSpec spectrographic data and False otherwise.  For NIRSpec imaging data, the reftype will then be flat, rather than fflat, sflat, and dflat.  In flat_field.py, call ``do_NIRSpec_flat_field`` only for NIRSpec spectrographic data; otherwise, call ``do_flat_field``.

**Comment by hbushouse** [comment]
Fixed by #634.
