### ISSUE TITLE
NIRCam distortion model needs updating

### ISSUE THREAD

**Issue by jdavies-st** [STScI-JWST/jwst#627]
Currently, `assign_wcs` for NIRCam imaging uses a reference file containing a distortion model computed from NIRCam SIAF file from Colin Cox using Bryan Hilbert's code `jwreftools/nircam/make_all_distortion_reffiles.py` on `github.com/spacetelescope`.

The model does the basic distortion and scaling from pixels to arcsec, but does not take into account the position of the aperture in the v2/v3 focal plane or the aperture reference pixel location.  So it does not go from science frame to v2v3 frame as we had thought it might.

Two corrections are possible:

1) Have Bryan remake the reference file(s) and deliver them with the shifts in detector and v2v3 (and possible rotation) added into the model.

or

2) Pull those shifts from the FITS header when `assign_wcs` is run in the pipeline, and have it create the correct transform.  The level 1 processing populates these header keywords from the SIAF file anyway, so we can just use these in `assign_wcs`.  Keywords needed are `CRPIX1, CRPIX1, V2_REF, V3_REF`

Would it be good to get more input from the rest of the NIRCam team?  It probably is important that whoever in the NIRCam team will be computing the on-sky distortion after launch know how we implement that distortion on our end.

Anyone have any thoughts on this?

@nden @hbushouse

**Comment by hbushouse** [comment]
Is it at all instructive to compare to the way the MIRI imaging distortion model is constructed? Does it contain these shifts relative to reference points? I'm always a fan of consistency. And something in me says I'd rather see all of the effects packaged/accounted for in a single place, rather than having to piece things together from calculations that are added after the fact to reference data.

**Comment by nden** [comment]
Looking through old emails I see Bryan reported that he thinks the V2_REF, V3_REF values should be added after the distortion. I have obviously forgotten about this (the importance of github issues!). 
Now @jdavies-st reports that we need to account for CRPIX as well. What worries me is that none of this comes from the NIRCAM team and has not been approved. since it's a semi-fake model I'd be against making new fake reference files and engaging several other people to deliver them. We could add the transforms to the NIRCAM WCS (assuming someone on the team tells us what they should be). 

Also it sounds like the NIRCAM team is not aware of the overall plan for imaging WCSs that the rest of the INS teams have adopted.  I agree with @hbushouse it's best to try to keep things consistent between instruments. We need a WCS contact person on the NIRCAM team.

**Comment by jdavies-st** [comment]
Thanks Nadia & Howard.  I agree that consistency across instruments would be good.  Image distortion reffiles from different instruments should be in the same basic format.  Also, I agree that it would be good to get the rest of the NIRCam team to commit to a format for the on-sky distortion model when it will be done for real during commissioning.  It is important that whatever software in the pipeline handles the current reffile also handle any future reffile.  It would be bad for different reffiles with different use-after dates to have to use different code within the pipeline, or for us to have to worry about code changes coinciding with reffile format changes at the same time during operations.

I suspect it would be fairly straightforward for Bryan to remake some new reffiles for NIRCam, taking into account of these offsets.  His code for doing this is on Github and it is well-written and documented.

**Comment by nden** [comment]
Fixed. The instrument team has made new reference files.
