### ISSUE TITLE
source_catalog needs to save segmentation map

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#739]
calspec2 processing of NIRCam and NIRISS grism exposures requires as input not only the source catalog produced by the source_catalog step from the associated direct images of the field, but also the segmentation map. Right now the source_catalog step doesn't save the segmentation map, so it needs to be updated to do so.

The segmentation map is a 2D image and hence we should be able to save it as a normal FITS file. For the sake of completeness the segmentation image should have all of the meta data copied over from the input image, including the WCS object info. We should probably create a data model (SegmentationModel?) for this file type, in order to make it as easy as possible to create it in source_catalog and to reload it in the assign_wcs step when it's needed for grism processing.

**Comment by sosey** [comment]
I think we can close this issue. I spoke with @larrybradley a while back and we added the sky coordinates (ra,dec) of the minimum bounding box corners to the source catalog, so the grisms no longer need the the segmentation map. However, I do need to know what the new column names are for the minimum bounding box corners. In the code, I've assumed they would be called:  `ramin` `decmin` `ramax` `decmax`, but need to change if larry called them otherwise

**Comment by larrybradley** [comment]
Yes, we are no longer planning to save the segmentation map.  The bounding box information will be stored in the source catalog, but those are not the correct column names.  The columns are named `sky_bbox_ll`, `sky_bbox_ul`, `sky_bbox_lr`, and `sky_bbox_ur`, each of which is a `SkyCoord` (i.e. RA & Dec & frame) at one corner of the minimal bounding box.  There will also be a `sky_bbox` property as a 4-tuple of `SkyCoord`, but that is not serializable (hence, the four separate columns).  This is not yet merged in `photutils` -- I discovered some bugs with `SkyCoord` and serialization, some of which have just been fixed in astropy.

**Comment by sosey** [comment]
excellent, I'll update my column names for extract2d, thanks.

**Comment by sosey** [comment]
@larrybradley I think there's still two columns with ra_icrs_centroid and dec_icrs_centroid in the source_catalog, are you planning on changing that to 1 `SkyCoord` column as well?

**Comment by larrybradley** [comment]
Yes, that's part of the same (unmerged) PR.
