### ISSUE TITLE
CRDS datamodels validation issues

### ISSUE THREAD

**Issue by jaytmiller** [STScI-JWST/jwst#796]
CRDS has a requirement to specify patterns of values in reference file headers.  For example,  rather than setting 

EXP_TYPE=NRS_IMAGE

(a real / physical value) CRDS needs to have reference specify the patterns of values to which they apply,  e.g.

EXP_TYPE=ALL_IMAGING

or more literally

EXP_TYPE=NRS_BOTA|NRS_CONFIRM|NRS_IMAGE|NRS_MIMF|NRS_TACONFIRM|NRS_TACQ|NRS_TASLIT

CRDS needs reference files to specify how they apply to datasets in order to support automatic rmap updates.   In my opinion,  for large (possibly even small) sets of files,  manual rmap updates are not feasible.

The perceived problems arise when attempting to validate reference files using datamodels,  which happens automatically when stpipe returns open models to cal steps.  ALL_IMAGING and it's literal translation are not in the schema enumeration so they will fail,  at best resulting in a spurious warning and unusable value.

In discussion,  the possibility of "not validating" reference files emerged,  the argument being that reference matching keywords are rarely/never used by the calibration code.   It is the dataset keyword values that are used,  and naively,  presumed to match the reference file versions,  but that is an oversimplification.

CRDS itself cannot skip some kind of validation during reference file ingest and rmap updates or invalid rmaps will be created.  However,   the notion that datamodels need to be satisfied for reference files is in question.    CRDS can already leverage the schema and apply them to or-barred combinations internally...  but those same or-bars that pass CRDS will fail the datamodels when the cal code is run.

Possible solutions to this CRDS problem are:

1. Drop validation of some matching keywords for reference file models,  but not dataset models.

2. Extend jointly used schema with extra non-physical cases to support CRDS.

3. Extend the data models code to handle the special case of or'ed combinations of existing values.

4. Override reference file schema to allow special values in that context only.

5. Use alternative keywords (P_EXPTYP instead of EXP_TYPE) to specify match patterns for CRDS,  only optionally add them to the cal-code schema.

**Comment by nden** [comment]
A possible implementation of this is in #715. In #715 the core schema is separated from the core reference_file schema and P_EXPTYP is used in reference files which allows their validation. I have tested this with the `distortion` schema and a new `DistortionModel`. but more work is necessary to finish it.

**Comment by hbushouse** [comment]
The option (#1) of not validating reference files when they're loaded for use in the cal pipeline is a viable solution, at least for the purpose of automated processing within the operations environment, where you're always retrieving ref files from CRDS. The presumption is that the ref files will have been validated on their own before ingest into CRDS and hence they don't need to be revalidated every time they're used in the cal pipeline. That approach, however, breaks down in the case of users running the cal pipeline off-line and supplying their own ref file overrides. If validation is not performed when the ref file is loaded into a data model, then errors in user-supplied ref files won't get caught - at least not until they cause some kind of real error in the pipeline.

I tend to not like options 2 and 3, because I don't think the cal pipeline data models and schemas that are used for science products should have any extensions or modifications in order to accommodate non-science products (i.e. reference files).

I also don't like the idea of 5, where we invent new sets of keyword names, because we've now lost the direct connection to the original keyword name used in science products.

So in my opinion, I favor 4 of all the options listed above, in which we use separate schemas to define and validate the contents of reference files, rather than having the ref file schemas inherit from the science product schemas. Many of the ref files use a certain set of common keywords and hence we may not even need to have all that many unique ref file schemas. Many of them could use the same basic schema. And even if that reference file schema contains more keyword definitions than are used in some ref files, it doesn't matter, because any keywords listed in the schema but not found in the file header will simply be ignored (unless the keyword is somehow tagged as being required).

Nadia started to head in this direction with #715, in terms of defining separate schema(s) for reference files that don't inherit the core science product schema. I think we should continue with getting that approach fully implemented. That way we'd also satisfy my objection to option 1, because user-supplied reference files would still receive validation checking when being loaded into the pipeline.

**Comment by bernie-simon** [comment]
As I see it, you are adding a new type of data to the headers of reference files, regular expressions (regexp). Since the asdf code already validates on type, what would be needed is a new method to handle validation of regexp. There's no need for a new field in the schema, just another supported type in the type field. The pseudocode for the validation would be something like this:

```
def validate_regexp(schema, value):
    # Each subvalue in the value must match at least
    # one choice in the enum 
    for subvalue in value.split("|"):
        match = False
        for choice in schema["enum"]:
            if subvalue matches choice:
                match = True
                break
        if not match:
            return False
    return True
```

**Comment by jaytmiller** [comment]
All of Howard's analysis makes sense to me.   A common thread with Bernie (which is very possibly a great work optimization) is that these keywords would be properly modeled in reference file schema... which really are different than dataset schema.     Accurate specialized schema for reference files definitely seem like the best possible world.   I particularly agree with Howard that making overrides work is important,  without that there will be a vicious cycle of untested references hitting CRDS cold and being kicked back for repairs.

One note about the P_ keywords:  they're coupled to the classic keywords by a convention,  so they're not entirely disjoint,  it's just a matter of advertising and learning that convention.

**Comment by nden** [comment]
@bernie-simon The regex validation is already supported in jsonschema using the `pattern` keyword.

**Comment by jaytmiller** [comment]
Relevant to P_ keywords,  Nadia reminded me:   at times it could be necessary to express both a physical value and a pattern of applicability.  On the CRDS side,  these "keywords" are currently used for matching:

{'fgs': ['META.INSTRUMENT.NAME',
  'META.EXPOSURE.READPATT',
  'META.EXPOSURE.TYPE',
  'META.INSTRUMENT.DETECTOR',
  'META.OBSERVATION.DATE',
  'META.OBSERVATION.TIME',
  'META.SUBARRAY.NAME',
  'REFTYPE'],
 'miri': ['META.INSTRUMENT.NAME',
  'META.EXPOSURE.READPATT',
  'META.EXPOSURE.TYPE',
  'META.INSTRUMENT.BAND',
  'META.INSTRUMENT.CHANNEL',
  'META.INSTRUMENT.DETECTOR',
  'META.INSTRUMENT.FILTER',
  'META.OBSERVATION.DATE',
  'META.OBSERVATION.TIME',
  'META.SUBARRAY.NAME',
  'REFTYPE'],
 'nircam': ['META.INSTRUMENT.NAME',
  'META.EXPOSURE.READPATT',
  'META.EXPOSURE.TYPE',
  'META.INSTRUMENT.CHANNEL',
  'META.INSTRUMENT.DETECTOR',
  'META.INSTRUMENT.FILTER',
  'META.INSTRUMENT.PUPIL',
  'META.OBSERVATION.DATE',
  'META.OBSERVATION.TIME',
  'META.SUBARRAY.NAME',
  'REFTYPE'],
 'niriss': ['META.INSTRUMENT.NAME',
  'META.EXPOSURE.READPATT',
  'META.EXPOSURE.TYPE',
  'META.INSTRUMENT.DETECTOR',
  'META.INSTRUMENT.FILTER',
  'META.INSTRUMENT.PUPIL',
  'META.OBSERVATION.DATE',
  'META.OBSERVATION.TIME',
  'META.SUBARRAY.NAME',
  'REFTYPE'],
 'nirspec': ['META.INSTRUMENT.NAME',
  'META.EXPOSURE.READPATT',
  'META.EXPOSURE.TYPE',
  'META.INSTRUMENT.DETECTOR',
  'META.INSTRUMENT.FILTER',
  'META.INSTRUMENT.GRATING',
  'META.OBSERVATION.DATE',
  'META.OBSERVATION.TIME',
  'META.SUBARRAY.NAME',
  'REFTYPE'],
 'system': ['META.INSTRUMENT.NAME',
  'META.CALIBRATION_SOFTWARE_VERSION',
  'META.OBSERVATION.DATE',
  'META.OBSERVATION.TIME',
  'REFTYPE']}

If any of those meet the criteria of wanting to know both,  then P_ might be necessary at least some of the time.  In the case of EXP_TYPE in particular,  I think it probably has to qualify,  because we just reclassified files of type NRS_IMAGE as applying to ALL_IMAGING (NRS).

**Comment by bernie-simon** [comment]
There are no changes to the validation code in pull request #715, only changes to the schema. Some new validation code will need to be written.

**Comment by jaytmiller** [comment]
OK.   Possibly we don't need both your "new type method" and Nadia's "fancy pattern method".   We may need a 1/2 hour meeting to decide what to do with everyone involved present.

**Comment by jaytmiller** [comment]
Ultimately this was resolved using the P_ keyword approach and pretty massive new support for reference file schema and pattern keyword validation.   Closing this.
