### ISSUE TITLE
Step.save_model alignment with Step saving

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#942]
# Implementation

- [x] honor `save_results`
- [x] allow option for file specification ala `output_file`-like configuration options _#1316_
- [x] inclusion of reference file usage and software version _#1218_

**Comment by stscieisenhamer** [comment]
## Comment about the reference file usage/software version
If step results are saved via standard step flow, at the end of the step, there are two pieces of information that are written into the results that are not when explicitly saving a result:

- CRDS info such as context and CRDS version
- software version and commit version

Since this seems to have gone unnoticed/ignored, the question is: should this actually happen?

A reason for is that `save_model` is often used to save final results, which the above info seems to be rather important for. But throwing out there in case there is reason not to.

**Comment by hbushouse** [comment]
I see no reason to NOT update everything like crds context, crds version, cal version, etc. whenever/however an output is created on disk. The fact that no one yet noticed that they weren't being set when using save_model is obviously simply because no one bothered to check. It's especially important if/when save_model is ever used to save a real product, like the way it was used a lot in the old calspec2 pipeline.

**Comment by hbushouse** [comment]
Any remaining work for this is being moved to B7.2

**Comment by stscieisenhamer** [comment]
Resolved by #1316
