### ISSUE TITLE
CubeBuildStep does not seem to setting the cal_step status

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#946]
This is based only on code inspection, but it appears the step status is not being set.

Since, functionally, `cube_build` seems to be an alternate algorithm for the resample steps, it could set `meta.cal_step.resample = 'COMPLETE'`.

Or, if not considered a "resample" step, it will need its own step defined in `core.schema` and set that status.

**Comment by hbushouse** [comment]
Since resample and cube_build are such different beasts right now, I'd opt for a dedicated S_CUBEBD (or some more clever 6-letter acronym) keyword, which means adding an entry to core.schema.yaml.  The tricky bit about setting the value is that in the case where cube_build is building multiple single cubes (for use in skymatch and outlier_detection) the status should theoretically be set in the meta data of every output cube.

**Comment by stscieisenhamer** [comment]
Resolved by #948
