### ISSUE TITLE
jwst/assign_wcs/tests/test_nirspec.py fails only on travis

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#967]
Of late the test
```
jwst/assign_wcs/tests/test_nirspec.py
```
has been failing in Travis ([recent build example](https://travis-ci.org/STScI-JWST/jwst/builds/241202979)). I cannot reproduce locally.

**Comment by hbushouse** [comment]
Perhaps a problem with the version of astropy or gwcs being used in Travis?

**Comment by nden** [comment]
I've looked into this and made a test PR which prints the version of astropy used in testing on Travis. Conda-dev uses the latest astropy, that's why we don't see the problem locally and in the nightly regression tests. For some reason, although Travis uses conda-dev, astropy is downgraded to a version which is ~ 500 commits earlier. I don't know why this happens. Unless @jhunkeler has any ideas the only way I can see this being fixed is to install astropy from master directly on Travis and not use the conda-dev installation.

**Comment by stscieisenhamer** [comment]
😞 That is odd. Doing a straight install of conda-dev, and an install of jwst/master, all works fine.

If this issue is not needed, go ahead and close.

**Comment by jdavies-st** [comment]
Very odd.  I don't see the test failing locally either.  But another oddity.  When I look at my conda-dev environment, updated today, I see:
```
(dev_b7) solo> conda list --explicit | grep astropy
http://ssb.stsci.edu/conda-dev/osx-64/astropy-2.0.dev6804-np112py35_1.tar.bz2
```
But when I load up astropy into python:
```
In [1]: import astropy

In [2]: astropy.__version__
Out[2]: '2.0.dev18562'
```
Hmm.  Is dev6804 == dev18562?

**Comment by nden** [comment]
conda-dev uses `git describe` to get the version. And yes, those seem equivalent. However, something forces astropy to be downgraded to an earlier version. 
I think this needs to stay open until it's resolved. If nothing better we can always force a direct astropy install from master.

**Comment by jdavies-st** [comment]
In Jonathan's recent build example above, the build with numpy 1.12 worked.  The others did not.  In our Travis setup, `NUMPY_VERSION=1.11` in the global environment, so I assume that is what is used for those builds.

 At some point did astropy dev start requiring numpy 1.12?

**Comment by jdavies-st** [comment]
Looking at [astropy Travis setup](https://github.com/astropy/astropy/blob/master/.travis.yml), it looks like they run tests with 1.11 as well.  Hmm.
